language: node_js
node_js: 
  - "7"
before_script:
  - npm i
cache:
  directories:
    - "node_modules"
script: 
  - npm run deploy
deploy:
  provider: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: gh-pages